### ISSUE TITLE
no search results

### ISSUE THREAD

**Issue by keeps21** [TradeMe/PlayMe#24]
When searching, the image of the artist is being returned, but no artist, track or album is found.

Any ideas?

![ozzy](https://cloud.githubusercontent.com/assets/6526263/8500479/71b49dc2-2194-11e5-96e4-6728b3efc1b3.JPG)

**Comment by fordprefect480** [comment]
Ozzy should definitely be returning results :p Also if no tracks found then it should not be trying to display artwork, so something's up. Any errors in the browser console?

**Comment by keeps21** [comment]
Checked the browser console - this is what is appearing:

Failed to load resource: the server responded with a status of 404 (Not Found)
core?v=56omQOHv45EsK-oLRS05e0Drqjf7lJpVk5iR9sIGv-81:1  /Content/fonts/glyphicons-halflings-regular.woff:1

Uncaught TypeError: Unable to process binding "with: function (){return results().PagedArtists }" core?v=56omQOHv45EsK-oLRS05e0Drqjf7lJpVk5iR9sIGv-81:1

Message: Unable to process binding "foreach: function (){return Artists }"
Message: Unable to process binding "truncated: function (){return Name }"
Message: r.truncate is not a function

**Comment by keeps21** [comment]
A little more info... The problem seems to be coming form the following line in web/scripts/BindingHandlers.js

$(element).text(valueUnwrapped.truncate(truncatedLength));

Commenting this out gets rid of the error and gets more results - but there's no titles, or anything to click on.

![Uploading ss.JPG…]()

**Comment by keeps21** [comment]
Fixed the .woff error

I've amended the first function in web/scripts/BindingHandlers.js a little to fix the 'truncate function error which is getting me further.

ko.bindingHandlers.truncated = {
    update: function (element, valueAccessor, allBindingsAccessor) {
	

        // First get the latest data that we're bound to
        var value = valueAccessor(), allBindings = allBindingsAccessor();

        // Next, whether or not the supplied model property is observable, get its current value
        var valueUnwrapped = ko.utils.unwrapObservable(value);

        var truncatedLength = allBindings.truncatedLength || 60;
       
        //$(element).text(valueUnwrapped.truncate(truncatedLength));
	$(element).text(valueUnwrapped.substring(0,60)); // stephen added this line
        $(element).attr("title", valueUnwrapped);
    }
};

No errors in the console now.

I can now see all albums, and click to get to the tracks but only 1 track is appearing per album. (presumably truncate is still being called somewhere?

Where should the r.truncate function, which was throwing the errors earlier, be?
![1](https://cloud.githubusercontent.com/assets/6526263/8599888/c6f09442-265a-11e5-980d-8a0b19f771a0.JPG)
![2](https://cloud.githubusercontent.com/assets/6526263/8599889/c6f1b05c-265a-11e5-84f2-7057255b83f3.JPG)
![3](https://cloud.githubusercontent.com/assets/6526263/8599890/c6f7a12e-265a-11e5-9ddb-445db13af9ce.JPG)

**Comment by keeps21** [comment]
Closed issue by accident so reopening now.

**Comment by fordprefect480** [comment]
OK, the truncate function should be getting called on all artist, album and tracknames so that should narrow it down a bit.

Also, to get admin menu to appear, you should have your DOMAIN/username in the config file before starting the service so doublecheck that. The UI pings the service which checks the config file so that shouldn't be too tricky to track down. Also, sometimes the service and IIS don't talk to each other if they start in the wrong order, so if you start the service first and then restart IIS/clear browser cache that can clear up weird UI/visibility bugs.

Just setting up an install from scratch again to see if I can repro your issues.

**Comment by keeps21** [comment]
Great - any luck with the clean install?

**Comment by fordprefect480** [comment]
I downloaded the source again as a zip using Github's 'Download ZIP' button, extracted code, built and set it up as per [the setup instructions](https://github.com/TradeMe/PlayMe/wiki/Setup) and it's running fine with no errors.

Did you set up from the source? or from the compiled version in ReadyToRun.zip?

**Comment by keeps21** [comment]
I used the compiled version in ReadyToRun.zip - I'll try a clean install using the source instead and see if I get any errors that way.

**Comment by keeps21** [comment]
Downloaded the source and compiled and it's working fine (well, there's some javascript errors on the admin page when adding users but I can live with that). 

Thanks for the help! :+1: 

![js errors](https://cloud.githubusercontent.com/assets/6526263/8696814/c84e7b4c-2ae7-11e5-86b4-2a1ac47f55de.JPG)

**Comment by fordprefect480** [comment]
Awesome :) At least that's a 500 error so it should be straight forward to debug. I'll also take a look at rebuilding that compiled zip.

**Comment by keeps21** [comment]
One thing I did notice this time was that when running PlayMe.Server.exe I saw a splash screen for Bass.dll or Bass.Net.dll, whereas when it wasn't working I never saw this splash screen - not sure if that's any help to you or not. :)

**Comment by fordprefect480** [comment]
Nah its always done that. Feature? ;)

**Comment by danielfaulknor** [comment]
Any chance of this new build? I'm having issues getting the code to build :(

**Comment by fordprefect480** [comment]
OK, have rebuilt the ReadyToRun.zip which includes a version of the website that worked for me. Could you let me know if it works for you? https://github.com/TradeMe/PlayMe/blob/master/ReadyToRun.zip

**Comment by alfiethecoder** [comment]
Has this been fixed? I downloaded the version listed above today, and then installed and ran it. I get the same issue - one icon, no search results are displayed.

![image](https://cloud.githubusercontent.com/assets/20190408/16422248/a0d50768-3d4f-11e6-8e92-e2e7758a145f.png)
